source 'http://rubygems.org'
gem 'middleman', '~> 3.4.0'
gem 'middleman-livereload', '~> 3.4.3'
gem 'middleman-minify-html', '~> 3.4.1'
gem 'middleman3-sassc', '~> 0.0.1'
gem 'uglifier', '~> 2.7.2'
gem 'therubyracer', '~> 0.12.2'
gem 'sprockets-babel', '~> 0.0.6'
gem 'babel-source', '~> 5.8.26'
